package code

import "strings"

import "testing"

func TestBlockDepth(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want int
	}{
		{"плоская функция", "// c\nfunc a() {\n\tx()\n}\n", 0},
		{"if и for - два уровня", "// c\nfunc a() {\n\tif x {\n\t\tfor y {\n\t\t\tz()\n\t\t}\n\t}\n}\n", 2},
		{"не функция", "// c\nvar x = 1\n", 0},
		{"пробелы по два", "// c\nfunction a() {\n  if (x) {\n    for (;;) {\n      z()\n    }\n  }\n}\n", 2},
		{"комментарий не задирает глубину", "// c\nfunc a() {\n\tif x {\n\t\tz()\n\t\t// заметка с отступом\n\t\t\t// и ещё глубже\n\t}\n}\n", 1},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			lines := strings.Split(c.src, "\n")
			if got := blockDepth(lines, 1); got != c.want {
				t.Fatalf("глубина %d, ожидалось %d", got, c.want)
			}
		})
	}
}

// Выравнивание продолжений даёт разрыв в 1-2 пробела. Шаг отступа по минимуму
// задирает глубину в разы: на замере так вышло 13.3% нарушителей вместо нуля.
func TestIndentUnitIgnoresAlignment(t *testing.T) {
	src := "func a(x int,\n       y int) {\n\tif x > 0 {\n\t\tz()\n\t}\n}\n"
	lines := strings.Split(src, "\n")
	if u := indentUnit(lines); u != 8 {
		t.Fatalf("шаг отступа %d, ожидался 8", u)
	}
	if d := blockDepth(lines, 0); d != 1 {
		t.Fatalf("глубина %d, ожидалась 1", d)
	}
}

// Совет должен меняться: над глубокой функцией чинить надо функцию.
func TestLongCommentOverDeepFunction(t *testing.T) {
	c := Comment{File: "a.go", Start: 1, Lines: 3,
		Text: "первая строка\nвторая строка\nтретья строка", Depth: 6}
	got := structChecks(2, 0, c)
	if len(got) == 0 {
		t.Fatal("правило не сработало")
	}
	if !strings.Contains(got[0].Fix, "fix the function") {
		t.Fatalf("совет не про функцию: %q", got[0].Fix)
	}
	c.Depth = 2
	if got = structChecks(2, 0, c); !strings.Contains(got[0].Fix, "Fit in") {
		t.Fatalf("на плоской функции совет должен остаться прежним: %q", got[0].Fix)
	}
}

// Файл со словом "@generated" в середине строки кода - не сгенерированный.
// Раньше comments.go из-за своей же регулярки не проверялся вовсе.
func TestGeneratedNeedsAnchor(t *testing.T) {
	if isGenerated([]byte("package a\n\nvar re = regexp.MustCompile(`@generated`)\n")) {
		t.Fatal("слово в коде принято за маркер")
	}
	for _, src := range []string{
		"// Code generated by stringer. DO NOT EDIT.\npackage a\n",
		"// @generated\npackage a\n",
		"/* @generated */\npackage a\n",
		"var x = 1\n//# sourceMappingURL=a.js.map\n",
	} {
		if !isGenerated([]byte(src)) {
			t.Fatalf("маркер не распознан: %q", src)
		}
	}
}
